funky/config/routes.rb
Funky::Application.routes.draw do
  resources :users
  resources :snippets
  resources :sessions,  only: [:new, :create, :destroy]
  resources :languages, only: [:index, :show]

  root to: 'static_pages#home'

  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  match '/about',     to: 'static_pages#about'
  match '/contribute', to: 'static_pages#contribute'

end

funky/app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :snippets

  validates :name, presence: true

  def to_param
    name
  end
end

funky/app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :content, :description, :source_link, :title, :language_id, :user_id

  belongs_to :user
  belongs_to :language

  before_save :create_slug

  validates :title, presence: true,
                    length: { maximum: 300 }
  validates :language_id, presence: true
  validates :user_id, presence: true

  def to_param
    slug
  end

  private

    def create_slug
      self.slug = SecureRandom.urlsafe_base64(15)
    end
end

funky/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :username
  has_secure_password

  has_many :snippets, dependent: :destroy

  before_save { email.downcase! }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true,
                       uniqueness: true,
                       length: { maximum: 50 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  def to_param
    username
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

funky/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

funky/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
  end

  def show
    @language = Language.find_by_name(params[:id])
  end
end

funky/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Successfully signed in."
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

funky/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy, :new, :create]
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def index
    @snippets = Snippet.all.sort_by { |s| s[:created_at] }.reverse
  end

  def show
    @snippet = Snippet.find_by_slug(params[:id])
  end

  def new
    @snippet = Snippet.new
    @snippet.user_id = current_user.id
    @languages = Language.all
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      flash[:success]= "Snippet Posted."
      redirect_to @snippet
    else
      @languages = Language.all
      render :new
    end
  end

  def edit
    @snippet = Snippet.find_by_slug(params[:id])
    @languages = Language.all
  end

  def update
    if @snippet.update_attributes(params[:snippet])
      flash[:success] = "Snippet Updated."
      redirect_to @snippet
    else
      @languages = Language.all
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to root_url
  end

  private

    def correct_user
      @snippet = current_user.snippets.find_by_slug(params[:id])
      redirect_to root_url if @snippet.nil?
    end
end

funky/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @snippets = Snippet.all.sort_by { |s| s[:created_at] }.reverse
  end

  def about
  end

  def contribute
  end
end

funky/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find_by_username(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success]= "Welcome to Funky!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_username(params[:id])
  end

  def update
    @user = User.find_by_username(params[:id])
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile Updated."
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by_username(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to root_url
  end

  private

    def correct_user
      redirect_to(root_url) unless signed_in?
      redirect_to(root_url) unless params[:id] == current_user.username
    end
end

funky/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    current_user.present?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

funky/app/helpers/snippets_helper.rb
module SnippetsHelper
end

funky/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar =
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

funky/app/views/languages/index.slim
- @languages.each do |language|
  div.language-item
    h3 = link_to language.name, language
    p = language.description

funky/app/views/languages/show.slim
h2 All #{@language.name} Snippets

- @language.snippets.each do |snippet|
  = render "shared/snippet", snippet: snippet

funky/app/views/layouts/_footer.slim
script src="http://yandex.st/highlightjs/7.3/highlight.min.js"

javascript:
  hljs.initHighlightingOnLoad();
  hljs.tabReplace = '    ';

funky/app/views/layouts/_header.slim
header.site-header
  h1 = link_to "Funky", root_url
  nav
    = link_to "View Snippets", snippets_url
    = link_to "View Languages", languages_url
    - if signed_in?
      = link_to "Profile", current_user
      = link_to "Sign Out", signout_path, method: "delete"
    - else
      = link_to "Sign Up", signup_path
      = link_to "Sign In", signin_path

- flash.each do |key, value|
  div class="alert alert-#{key}" = value

funky/app/views/layouts/application.slim
doctype html
html
  head
    title Funky
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    link href="http://fonts.googleapis.com/css?family=Galindo" rel="stylesheet"

  body

    = render "layouts/header"

    div.main
      = yield

    = render "layouts/footer"

funky/app/views/shared/_error_messages.slim
- if object.errors.any?
  div.error-explanation
    div.alert.alert-error
      | The form contains #{pluralize(object.errors.count, "error")}
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

funky/app/views/shared/_snippet.slim
div.snippet
  - if !request.url.include? "users"
    p style="float: right"
      = gravatar_for snippet.user
      = " "
      = link_to snippet.user.username, snippet.user

  h3 = link_to snippet.title, snippet
  small: em = snippet.language.name
  p = snippet.description
  p = link_to "Original", snippet.source_link unless snippet.source_link.empty?
  pre: code class="#{snippet.language.name.downcase}"
      = snippet.content

funky/app/views/snippets/edit.slim
div.new-snippet
  h1 Edit Snippet
  = form_for(@snippet) do |f|
    = render 'shared/error_messages', object: f.object

    br
    = f.label :title
    = f.text_field :title

    = f.label :language_id
    = select_tag "snippet[language_id]", \
                  options_for_select(@languages.map { |n| [n.name, n.id] })
    br
    = f.label :source_link, "Link to original source"
    = f.text_field :source_link, placeholder: "Optional"
    br
    = f.label :description
    = f.text_area :description, placeholder: "Optional"
    br
    = f.label :content, "Code"
    = f.text_area :content, class: "snippet-code-form"
    br

    = f.submit "Update Snippet"

funky/app/views/snippets/index.slim
- unless Language.all.empty?
	a style="float: right" href="/snippets/new" Create a code snippet

h2 All Snippets

- @snippets.each do |snippet|
  = render "shared/snippet", snippet: snippet

funky/app/views/snippets/new.slim
div.new-snippet
  h1 Add a new snippet
  = form_for(@snippet) do |f|
    = render 'shared/error_messages', object: f.object
    = f.hidden_field :user_id, value: current_user.id

    br
    = f.label :title
    = f.text_field :title

    = f.label :language_id
    = select_tag "snippet[language_id]", \
                  options_for_select(@languages.map { |n| [n.name, n.id] })
    br
    = f.label :source_link, "Link to original source"
    = f.text_field :source_link, placeholder: "Optional"
    br
    = f.label :description
    = f.text_area :description, placeholder: "Optional"
    br
    = f.label :content, "Code"
    = f.text_area :content, class: "snippet-code-form"
    br

    = f.submit "Submit Snippet"

funky/app/views/snippets/show.slim
- if current_user == @snippet.user
  = link_to "Edit Snippet", edit_snippet_path

= render "shared/snippet", snippet: @snippet

funky/app/views/static_pages/about.slim
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

funky/app/views/static_pages/contribute.slim
<h1>StaticPages#contribute</h1>
<p>Find me in app/views/static_pages/contribute.html.erb</p>

funky/app/views/static_pages/home.slim
div.greeting
  h1
    | Funky lets you
    em  share
    |,
    em  discover
    |, and
    em  keep track
    |  of code snippets.
  p Take a look at the most recent snippets and see what you can learn.

- @snippets.each do |snippet|
  = render "shared/snippet", snippet: snippet

funky/app/views/users/edit.slim
div.sign-up
  h2 Edit Profile

  = form_for(current_user) do |f|
    = render 'shared/error_messages', object: f.object

    = f.label :username
    = f.text_field :username
    br
    = f.label :email
    = f.email_field :email
    br
    = f.label :password
    = f.password_field :password
    br
    = f.submit "Update Profile"

funky/app/views/users/new.slim
div.sign-up
  h2 Sign Up

  = form_for(@user) do |f|
    = render 'shared/error_messages', object: f.object
    br
    = f.label :username
    = f.text_field :username
    br
    = f.label :email
    = f.email_field :email
    br
    = f.label :password
    = f.password_field :password
    br

    = f.submit "Create your account"

funky/app/views/users/show.slim
div.profile
  = gravatar_for @user
  h1 = " " + @user.username
  p = @user.email

  - if current_user == @user
    = link_to "Edit Profile", edit_user_path

  br: br

  h3 #{@user.username}'s snippets
  - @user.snippets.each do |snippet|
    = render "shared/snippet", snippet: snippet